JS課題「Promise」
Kenta-Tanamachi/comsica-hideki-JSLevelUpProject pull request #4
Opened 2022-05-06 10:48 UTC by hideki1516

# promiseの練習-01
出力結果を「結果→終了」と表示されるように修正を加えました。
ご確認をお願いいたします。

2022-05-11 04:51 UTC, Kenta-Tanamachi requested changes

2022-05-11 04:51 UTC, Kenta-Tanamachi commented on task/promiseTest.ts
> +  timeLoop().then((res) => console.log(res));
thenの構文は非推奨となっています〜
理由としてはthenの後にロジックを書かなくてはいけなく、可読性が低い（と考えられる）ためです。

他の方法でお願いします！

2022-05-11 04:51 UTC, Kenta-Tanamachi commented
PRのタイトルは日本語名で簡潔につけるのがわかりやすいのでおすすめです！

2022-05-14 08:08 UTC, hideki1516 commented on task/promiseTest.ts
> +  timeLoop().then((res) => console.log(res));
async・awaitを使用して修正対応しました。
ご確認をお願いいたします。

2022-05-17 10:56 UTC, Kenta-Tanamachi commented on task/promiseTest.ts
> +import { resolve } from 'path';
未使用のimportは極力PR時には消すようにしたほうがよいです

2022-05-17 10:56 UTC, Kenta-Tanamachi commented on task/promiseTest.ts
> +  const endMessage = async () => {
「関数の中に関数を書く」のはやらなくてはいけない理由がない限りは避けた方がよいです。
関数は極力ひとつづつ独立させた方が可読性がよいです〜

2022-05-17 10:56 UTC, Kenta-Tanamachi commented
あとPRのタイトルは一番上の部分です！

2022-05-23 12:25 UTC, hideki1516 commented on task/promiseTest.ts
> +import { resolve } from 'path';
未使用のimportを削除しました。

2022-05-23 12:29 UTC, hideki1516 commented on task/promiseTest.ts
> +import { resolve } from 'path';
未使用のimportを削除しました。

2022-05-23 12:30 UTC, hideki1516 commented on task/promiseTest.ts
> +  const endMessage = async () => {
関数の処理を修正しました。

2022-05-23 12:36 UTC, Kenta-Tanamachi approved these changes

2022-05-23 12:36 UTC, merged